name: Gym Scraper Test

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *' # Každých 30 minut
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    # Povolení pro zápis do repozitáře
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager beautifulsoup4

      - name: Run scraper
        run: python google_scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GymBot"
          git config --global user.email "bot@gym.cz"
          git add data.json
          git commit -m "Update occupancy data [skip ci]" || exit 0
          git push